apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
android {
    namespace 'com.stringee.apptoappcallsample'
    compileSdk = 36
    defaultConfig {
        applicationId "com.stringee.onetoonecallsample"
        minSdkVersion 24
        targetSdk 35
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        viewBinding true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    packagingOptions {
        resources {
            excludes += ['META-INF/LICENSE.txt', 'META-INF/LICENSE', 'META-INF/NOTICE.txt', 'META-INF/NOTICE', 'META-INF/DEPENDENCIES.txt', 'META-INF/DEPENDENCIES']
        }
    }


}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar", "*.aar"])
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.android.volley:volley:1.2.1'
    implementation 'androidx.core:core:1.18.0'
    implementation 'com.stringee.sdk.android:stringee-android-sdk:2.1.10'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'io.github.webrtc-sdk:android:137.7151.05'
    implementation platform("com.google.firebase:firebase-bom:34.13.0")
    implementation 'com.google.firebase:firebase-messaging'
}
