apply plugin: 'com.android.application'

if (file('google-services.json').exists()) {
    apply plugin: 'com.google.gms.google-services'
}
android {
    namespace 'com.stringee.apptoappcallsample'
    compileSdk = 36
    defaultConfig {
        applicationId "com.stringee.onetoonecallsample"
        minSdkVersion 24
        targetSdk 36
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        viewBinding true
    }

    testOptions {
        unitTests.includeAndroidResources = true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packagingOptions {
        resources {
            excludes += ['META-INF/LICENSE.txt', 'META-INF/LICENSE', 'META-INF/NOTICE.txt', 'META-INF/NOTICE', 'META-INF/DEPENDENCIES.txt', 'META-INF/DEPENDENCIES']
        }
    }


}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar", "*.aar"])
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.core:core:1.18.0'
    implementation 'com.stringee.sdk.android:stringee-android-sdk:2.1.13'
    implementation 'io.github.webrtc-sdk:android:144.7559.09'
    implementation platform("com.google.firebase:firebase-bom:34.17.0")
    implementation 'com.google.firebase:firebase-messaging'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'androidx.test:core:1.7.0'
    testImplementation 'org.robolectric:robolectric:4.16.1'
}

apply from: rootProject.file('../gradle/coverage.gradle')
