package com.stringee.video_conference_sample.main;

import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.util.Log;

import androidx.lifecycle.MutableLiveData;

import com.stringee.video_conference_sample.stringee_wrapper.common.PermissionsUtils;
import com.stringee.video_conference_sample.stringee_wrapper.common.Utils;
import com.stringee.video_conference_sample.stringee_wrapper.ui.activity.CheckDeviceActivity;
import com.stringee.video_conference_sample.stringee_wrapper.ui.base.MyViewModel;
import com.stringee.video_conference_sample.stringee_wrapper.wrapper.StringeeWrapper;
import com.stringee.video_conference_sample.stringee_wrapper.wrapper.listener.ConnectionListener;

public class MainViewModel extends MyViewModel {

    private static final String PREFS_NAME = "video_conference_sample";
    private static final String PREF_ACCESS_TOKEN = "last_connected_token";

    public enum MainState {
        CONNECT_CLIENT,
        CONNECT_ROOM
    }

    private String accessToken;
    private ConnectionTokenState connectionTokenState;
    private String roomName;
    private MutableLiveData<String> roomToken = new MutableLiveData<>();
    private final MutableLiveData<String> connectStatus = new MutableLiveData<>();
    private final MutableLiveData<Boolean> needRequestPermission = new MutableLiveData<>(false);
    private final MutableLiveData<MainState> mainState = new MutableLiveData<>(MainState.CONNECT_CLIENT);
    private final MutableLiveData<String> msg = new MutableLiveData<>();

    public MutableLiveData<Boolean> getNeedRequestPermission() {
        return needRequestPermission;
    }

    public MutableLiveData<MainState> getMainState() {
        return mainState;
    }

    public String getAccessToken() {
        return accessToken;
    }

    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    public MutableLiveData<String> getRoomToken() {
        return roomToken;
    }

    public void setRoomToken(MutableLiveData<String> roomToken) {
        this.roomToken = roomToken;
    }

    public MutableLiveData<String> getMsg() {
        return msg;
    }

    public MutableLiveData<String> getConnectStatus() {
        return connectStatus;
    }

    public void connectClient(Context context) {
        ensureTokenState(context);
        if (!ConferenceInputPolicy.isValidAccessToken(accessToken)) {
            msg.setValue("Please enter an access token generated by your server");
            return;
        }

        String tokenToConnect = connectionTokenState.beginConnect(accessToken);
        if (tokenToConnect.isEmpty()) {
            return;
        }

        StringeeWrapper.getInstance(context).setConnectionListener(new ConnectionListener() {
            @Override
            public void onConnected(String userId) {
                Utils.runOnUiThread(() -> {
                    Log.d("Stringee", "onConnected: " + userId);
                    connectStatus.setValue("Connected as " + userId);
                    String successfulToken = connectionTokenState.onConnected();
                    if (!successfulToken.isEmpty()) {
                        context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
                                .edit()
                                .putString(PREF_ACCESS_TOKEN, successfulToken)
                                .apply();
                    }
                    mainState.setValue(MainState.CONNECT_ROOM);
                });
            }

            @Override
            public void onDisconnected() {
                Utils.runOnUiThread(() -> {
                    Log.d("Stringee", "Disconnected");
                    connectionTokenState.onConnectionError();
                    connectStatus.setValue("Disconnected");
                    mainState.setValue(MainState.CONNECT_CLIENT);
                });
            }

            @Override
            public void onConnectionError(String error) {
                Utils.runOnUiThread(() -> {
                    Log.d("Stringee", "onConnectionError: " + error);
                    connectionTokenState.onConnectionError();
                    connectStatus.setValue("Connection error: " + error);
                    mainState.setValue(MainState.CONNECT_CLIENT);
                });
            }

            @Override
            public void onRequestNewToken() {
                Utils.runOnUiThread(() -> {
                    Log.d("Stringee", "onRequestNewToken");
                    connectStatus.setValue("Request new token");
                });
            }
        });
        accessToken = tokenToConnect;
        connectStatus.setValue("Connecting…");
        StringeeWrapper.getInstance(context).connect(tokenToConnect);
    }

    public void initialize(Context context) {
        ensureTokenState(context);
        String savedToken = connectionTokenState.consumeAutoConnectToken();
        if (!savedToken.isEmpty()) {
            accessToken = savedToken;
            connectClient(context);
        }
    }

    public void connectRoom(Context context) {
        if (!StringeeWrapper.getInstance(context).isConnected()) {
            msg.setValue("Please connect before connecting room");
            return;
        }

        if (!ConferenceInputPolicy.isValidRoomToken(roomToken.getValue())) {
            msg.setValue("Please enter a room token generated by your server");
            return;
        }

        if (!PermissionsUtils.getInstance().checkSelfConferencePermission(context)) {
            needRequestPermission.setValue(true);
            return;
        }

        needRequestPermission.setValue(false);
        String normalizedRoomToken = ConferenceInputPolicy.normalizeToken(roomToken.getValue());
        roomToken.setValue(normalizedRoomToken);
        StringeeWrapper.getInstance(context).createConferenceWrapper(normalizedRoomToken);
        Intent intent = new Intent(context, CheckDeviceActivity.class);
        intent.putExtra("room_name", "Stringee room");
        context.startActivity(intent);
    }

    public void backPress(Context context) {
        StringeeWrapper.getInstance(context).release();
        mainState.setValue(MainState.CONNECT_CLIENT);
        roomToken.setValue(null);
    }

    private void ensureTokenState(Context context) {
        if (connectionTokenState != null) {
            return;
        }
        SharedPreferences preferences = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE);
        connectionTokenState = new ConnectionTokenState(
                preferences.getString(PREF_ACCESS_TOKEN, ""));
    }
}
